# Generated by Django 5.1.4 on 2025-01-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letstalkapp', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='messages',
        ),
    ]
