# Generated by Django 5.0 on 2025-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letstalkapp', '0003_rename_message_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='checkuser',
            field=models.IntegerField(null=True),
        ),
    ]
